#!/usr/bin/env bash
# Aiu - UserBot
# Copyright (C) 2023-2024 AIUUSERBOT
#
# This file is a part of < https://github.com/JIYOXC/AIU-USERBOT/ >
# PLease read the GNU Affero General Public License in <https://github.com/JIYOXC/AIU-USERBOT/blob/main/LICENSE/>.


echo "
            闩工ㄩ ㄩ丂㠪尺乃龱ㄒ

      Visit @AIUSUPPORT for updates!!

"
if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then wget https://gist.github.com/1Danish-00/6554f034549197e5824972b01f631e0c/raw/main.py && python3 main.py ; else python3 -m pyUltroid ; fi
